version: '3.9'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:14
    ports:
      - 5432:5432
    restart: unless-stopped
    networks:
      - activepoints
    environment:
      - POSTGRES_USER=akuma
      - POSTGRES_PASSWORD=MyPassword
      - POSTGRES_DB=activepointsplusdb
    volumes:
      - postgres_data:/var/lib/db/data/
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@peervest.tech}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin123}
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin:/var/lib/pgadmin

    ports:
      - "${PGADMIN_PORT:-5050}:80"
    restart: unless-stopped
  mailhog:
    image: mailhog/mailhog
    ports:
      - 8025:8025
      - 1025:1025
    hostname: mailhog
    restart: always
    networks:
      - activepoints

volumes:
  postgres_data:
  pgdata:
  pgadmin:
networks:
  activepoints: {}