# Generated by Django 4.1.2 on 2022-10-24 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_profile_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_agent_info',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
