# Generated by Django 4.1.2 on 2022-10-26 01:54

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('traka', '0002_alter_profile_options_profile_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(default=datetime.datetime(2022, 10, 26, 1, 54, 55, 203379, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
    ]
